secret_id: your_secret_id
secret_key: your_secret_key
sleep_time: 120
domains:
    example.com:
        subdomain: 
            - 'A'
            - 'AAAA'
        subdomain2: 
            - 'A'
            - 'AAAA'
